image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      docker-compose up --build
      docker-compose run --rm api python3 manage.py migrate
      docker-compose run --rm api python3 manage.py createsuperuser --email admin@example.com --password admin
    command: docker-compose up
